version: '3.8'

services:
    #service 1: definition of mysql database
  db:
    image: jeickt/southsystem-desafio2:mysql
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=3698741
      - MYSQL_USER=jeickt
      - MYSQL_PASSWORD=3698741 
    ports:
      - "3306:3306"
    volumes:
      - desafio2=/var/lib/mysql
    restart: always
    
    #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: jeickt/southsystem-desafio2:phpmyadmin
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always
        
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3698741
    
    #service 3: definition of your spring-boot app 
  customerservice:                              #it is just a name, which will be used only in this file.
    image: jeickt/southsystem-desafio2:desafio2 #name of the image after dockerfile executes
    container_name: desafio2                    #name of the container created from docker image
    ports:
      - "8080:8080"                                  #docker containter port with your os port
    restart: always
       
    depends_on:                                 #define dependencies of this app
      - db                                      #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/desafio2?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3698741
        
volumes:
  desafio2: